// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfJDtv4-nl4LCjweDViubJpUIry1YN3FA',
    appId: '1:540544502845:web:1d765f94947b7d1c8bee54',
    messagingSenderId: '540544502845',
    projectId: 'learnflutter-rayen',
    authDomain: 'learnflutter-rayen.firebaseapp.com',
    storageBucket: 'learnflutter-rayen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYsrQkzrP_h2TmZFPw2iJKO_BTdWjmUw4',
    appId: '1:540544502845:android:9e9f7f20b55d96108bee54',
    messagingSenderId: '540544502845',
    projectId: 'learnflutter-rayen',
    storageBucket: 'learnflutter-rayen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5Pe1uNw_KleOt1ThP-D1Cmw_nEGqje0',
    appId: '1:540544502845:ios:6046a0946e1721d88bee54',
    messagingSenderId: '540544502845',
    projectId: 'learnflutter-rayen',
    storageBucket: 'learnflutter-rayen.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5Pe1uNw_KleOt1ThP-D1Cmw_nEGqje0',
    appId: '1:540544502845:ios:6046a0946e1721d88bee54',
    messagingSenderId: '540544502845',
    projectId: 'learnflutter-rayen',
    storageBucket: 'learnflutter-rayen.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfJDtv4-nl4LCjweDViubJpUIry1YN3FA',
    appId: '1:540544502845:web:dc7d794bceb3b4b48bee54',
    messagingSenderId: '540544502845',
    projectId: 'learnflutter-rayen',
    authDomain: 'learnflutter-rayen.firebaseapp.com',
    storageBucket: 'learnflutter-rayen.firebasestorage.app',
  );
}
