class UnableToGetDocumentsDirectory implements Exception {}
class DatabaseAlreadyOpenException implements Exception {}
class DatabaseIsNotOpenException implements Exception {}
class CouldNotDeleteUser implements Exception {}
class UserAlreadyExistsException implements Exception {}
class CouldNotFindUserException implements Exception {}
class CouldNotDeleteNote implements Exception {}
class CouldNotFindNoteException implements Exception {}
class CouldNotUpdateNote implements Exception {}
class UserShouldBeSetBeforeReadingAllNotes implements Exception {}